/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3053cc38-9e2a-4c03-9103-6c9f93b75ad0",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_4dSh36Y3c",
    "aws_user_pools_web_client_id": "1calj7b0mmta82ulbrt4149s9g",
    "oauth": {}
};


export default awsmobile;
